import type { GameId, GameMeta } from "@/types/game";

const g = (a: string, b: string) => `linear-gradient(135deg,${a},${b})`;

export const GAME_REGISTRY: Record<GameId, GameMeta> = {
  // ── Board games (2-player) ──────────────────────────────────────────────────
  chess: {
    id: "chess", name: "Chess",
    description: "The classic game of kings. Checkmate your opponent.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 30,
    tags: ["board", "strategy", "classic"],
    component: "chess/ChessBoard",
    color: g("#334155", "#0f172a"),
  },
  wordgrid: {
    id: "wordgrid", name: "Word Grid",
    description: "Place letter tiles on the board to form words and rack up points.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 45,
    tags: ["board", "classic"],
    component: "wordgrid/WordGridBoard",
    color: g("#b45309", "#78350f"),
  },
  backgammon: {
    id: "backgammon", name: "Backgammon",
    description: "Race your pieces home. Roll dice, outmanoeuvre your rival.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "classic", "strategy"],
    component: "backgammon/BackgammonBoard",
    color: g("#92400e", "#451a03"),
  },
  go: {
    id: "go", name: "Go",
    description: "Ancient strategy. Simple rules, infinite depth.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 60,
    tags: ["board", "strategy", "classic"],
    component: "go/GoBoard",
    color: g("#44403c", "#1c1917"),
  },
  checkers: {
    id: "checkers", name: "Checkers",
    description: "Jump over your opponent's pieces. King me.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "classic", "strategy"],
    component: "checkers/CheckersBoard",
    color: g("#991b1b", "#450a0a"),
  },
  fourinarow: {
    id: "fourinarow", name: "Four in a Row",
    description: "Drop discs into the grid. First to line up four wins.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 10,
    tags: ["board", "classic"],
    component: "fourinarow/FourInARowBoard",
    color: g("#1d4ed8", "#312e81"),
  },
  tictactoe: {
    id: "tictactoe", name: "Tic Tac Toe",
    description: "X vs O. Simple, fast, surprisingly competitive.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 2,
    tags: ["board", "classic"],
    component: "tictactoe/TicTacToeBoard",
    color: g("#7c3aed", "#4c1d95"),
  },
  reversi: {
    id: "reversi", name: "Reversi",
    description: "Flip your opponent's discs. Control the board.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "strategy", "classic"],
    component: "reversi/ReversiBoard",
    color: g("#15803d", "#14532d"),
  },
  mancala: {
    id: "mancala", name: "Mancala",
    description: "Sow seeds, capture pits, fill your store.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 15,
    tags: ["board", "classic", "strategy"],
    component: "mancala/MancalaBoard",
    color: g("#92400e", "#3b1a08"),
  },
  seabattle: {
    id: "seabattle", name: "Sea Battle",
    description: "Place your fleet and sink your opponent's ships.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "strategy", "classic"],
    component: "seabattle/SeaBattleBoard",
    color: g("#1e40af", "#0f172a"),
  },

  // ── Card games ────────────────────────────────────────────────────────────
  war: {
    id: "war", name: "War",
    description: "Flip cards and battle. Highest card wins the pile.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 15,
    tags: ["card", "classic"],
    component: "war/WarBoard",
    color: g("#dc2626", "#7f1d1d"),
  },
  blackjack: {
    id: "blackjack", name: "Blackjack",
    description: "Beat the dealer. Hit or stand to reach 21.",
    minPlayers: 1, maxPlayers: 6, estimatedMinutes: 20,
    tags: ["card", "classic"],
    component: "blackjack/BlackjackBoard",
    color: g("#15803d", "#052e16"),
  },
  wildcards: {
    id: "wildcards", name: "Wild Cards",
    description: "Match colors and numbers. Play action cards to shake things up.",
    minPlayers: 2, maxPlayers: 4, estimatedMinutes: 30,
    tags: ["card", "classic", "action"],
    component: "_stub",
    color: g("#dc2626", "#7c2d12"),
  },
  crazyeights: {
    id: "crazyeights", name: "Crazy Eights",
    description: "Play matching suit or rank. Eights are wild!",
    minPlayers: 2, maxPlayers: 4, estimatedMinutes: 20,
    tags: ["card", "classic"],
    component: "_stub",
    color: g("#7c3aed", "#3b0764"),
  },
  gofish: {
    id: "gofish", name: "Go Fish",
    description: "Collect sets of four by asking opponents for cards.",
    minPlayers: 2, maxPlayers: 4, estimatedMinutes: 15,
    tags: ["card", "classic"],
    component: "_stub",
    color: g("#0369a1", "#082f49"),
  },
  poker: {
    id: "poker", name: "Poker",
    description: "Texas Hold'em. Bluff, bet, and read the table.",
    minPlayers: 2, maxPlayers: 6, estimatedMinutes: 45,
    tags: ["card", "strategy", "classic"],
    component: "_stub",
    color: g("#166534", "#052e16"),
  },
  snap: {
    id: "snap", name: "Snap",
    description: "React fast — shout Snap when matching cards appear!",
    minPlayers: 2, maxPlayers: 4, estimatedMinutes: 10,
    tags: ["card", "classic", "action"],
    component: "_stub",
    color: g("#ea580c", "#431407"),
  },
  hearts: {
    id: "hearts", name: "Hearts",
    description: "Avoid hearts and the Queen of Spades. Shoot the moon!",
    minPlayers: 4, maxPlayers: 4, estimatedMinutes: 30,
    tags: ["card", "strategy", "classic"],
    component: "_stub",
    color: g("#be185d", "#500724"),
  },
  rummy: {
    id: "rummy", name: "Rummy",
    description: "Form sets and runs. First to empty your hand wins.",
    minPlayers: 2, maxPlayers: 4, estimatedMinutes: 30,
    tags: ["card", "classic"],
    component: "_stub",
    color: g("#d97706", "#451a03"),
  },

  // ── Multi-player extras ───────────────────────────────────────────────────
  fivedice: {
    id: "fivedice", name: "Five Dice",
    description: "Roll five dice and score combinations. Roll five of a kind for the jackpot!",
    minPlayers: 2, maxPlayers: 6, estimatedMinutes: 30,
    tags: ["dice", "classic"],
    component: "_stub",
    color: g("#0891b2", "#083344"),
  },
  liarsdice: {
    id: "liarsdice", name: "Liar's Dice",
    description: "Bluff with hidden dice. Call out liars or face the forfeit.",
    minPlayers: 2, maxPlayers: 6, estimatedMinutes: 20,
    tags: ["dice", "strategy", "classic"],
    component: "_stub",
    color: g("#6d28d9", "#1e0750"),
  },
  dominoes: {
    id: "dominoes", name: "Dominoes",
    description: "Match tiles end-to-end. Block your opponents and clear your hand.",
    minPlayers: 2, maxPlayers: 4, estimatedMinutes: 20,
    tags: ["board", "classic"],
    component: "_stub",
    color: g("#374151", "#030712"),
  },
};

export const GAMES = Object.values(GAME_REGISTRY);
