import type { GameId, GameMeta } from "@/types/game";

export const GAME_REGISTRY: Record<GameId, GameMeta> = {
  chess: {
    id: "chess",
    name: "Chess",
    description: "The classic game of kings. Checkmate your opponent.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 30,
    tags: ["board", "strategy", "classic"],
    component: "chess/ChessBoard",
    logo: "♟️", color: "from-slate-700 to-slate-900",
  },
  scrabble: {
    id: "scrabble",
    name: "Scrabble",
    description: "Build words, rack up points.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 45,
    tags: ["board", "classic"],
    component: "scrabble/ScrabbleBoard",
    logo: "🔤", color: "from-amber-600 to-amber-800",
  },
  backgammon: {
    id: "backgammon",
    name: "Backgammon",
    description: "Race your pieces home. Roll dice, outmanoeuvre your rival.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "classic", "strategy"],
    component: "backgammon/BackgammonBoard",
    logo: "🎲", color: "from-stone-600 to-amber-800",
  },
  go: {
    id: "go",
    name: "Go",
    description: "Ancient strategy. Simple rules, infinite depth.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 60,
    tags: ["board", "strategy", "classic"],
    component: "go/GoBoard",
    logo: "⚫", color: "from-stone-700 to-stone-900",
  },
  battleship: {
    id: "battleship",
    name: "Battleship",
    description: "Hidden fleets, deadly salvos. Sink them all.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 15,
    tags: ["board", "classic"],
    component: "battleship/BattleshipBoard",
    logo: "🚢", color: "from-blue-800 to-sky-950",
  },
  uno: {
    id: "uno",
    name: "Uno",
    description: "Play cards, draw penalties, shout UNO!",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 15,
    tags: ["card", "classic"],
    component: "uno/UnoGame",
    logo: "🃏", color: "from-red-600 to-orange-700",
  },
  pong: {
    id: "pong",
    name: "Pong",
    description: "The original arcade classic. First to 7 wins.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 5,
    tags: ["arcade", "classic"],
    component: "pong/PongCanvas",
    logo: "🏓", color: "from-cyan-600 to-teal-800",
  },
  streetfighter: {
    id: "streetfighter",
    name: "Street Fighter",
    description: "Choose your fighter. Land combos. Win the round.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 5,
    tags: ["fighting", "action"],
    component: "streetfighter/FightCanvas",
    logo: "👊", color: "from-red-700 to-rose-900",
  },
  checkers: {
    id: "checkers",
    name: "Checkers",
    description: "Jump over your opponent's pieces. King me.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "classic", "strategy"],
    component: "checkers/CheckersBoard",
    logo: "🔴", color: "from-red-700 to-red-950",
  },
  connect4: {
    id: "connect4",
    name: "Connect 4",
    description: "Drop discs, get four in a row.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 10,
    tags: ["board", "classic"],
    component: "connect4/Connect4Board",
    logo: "🔵", color: "from-blue-600 to-indigo-800",
  },
  tictactoe: {
    id: "tictactoe",
    name: "Tic Tac Toe",
    description: "X vs O. Simple, fast, surprisingly competitive.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 2,
    tags: ["board", "classic"],
    component: "tictactoe/TicTacToeBoard",
    logo: "✖️", color: "from-violet-600 to-purple-900",
  },
  reversi: {
    id: "reversi",
    name: "Reversi",
    description: "Flip your opponent's discs. Control the board.",
    minPlayers: 2, maxPlayers: 2, estimatedMinutes: 20,
    tags: ["board", "strategy", "classic"],
    component: "reversi/ReversiBoard",
    logo: "🟢", color: "from-green-700 to-emerald-900",
  },
};

export const GAMES = Object.values(GAME_REGISTRY);
